import type { AsciiChar, AsciiSettings } from './types'

const canvas = document.createElement('canvas')
const ctx = canvas.getContext('2d', { willReadFrequently: true })!

export function imageToAscii(
  source: HTMLImageElement | HTMLVideoElement | HTMLCanvasElement,
  settings: AsciiSettings,
  outputWidth?: number
): AsciiChar[][] {
  const cols = outputWidth ?? settings.density
  const srcW = source instanceof HTMLVideoElement ? source.videoWidth : source.width
  const srcH = source instanceof HTMLVideoElement ? source.videoHeight : source.height

  if (!srcW || !srcH) return []

  const aspect = srcH / srcW
  const charAspect = 0.5 // chars are ~2x tall as wide
  const rows = Math.floor(cols * aspect * charAspect)

  canvas.width = cols
  canvas.height = rows
  ctx.drawImage(source, 0, 0, cols, rows)

  const imageData = ctx.getImageData(0, 0, cols, rows)
  const pixels = imageData.data
  const chars = settings.charset
  const result: AsciiChar[][] = []

  for (let y = 0; y < rows; y++) {
    const row: AsciiChar[] = []
    for (let x = 0; x < cols; x++) {
      const i = (y * cols + x) * 4
      let r = pixels[i]
      let g = pixels[i + 1]
      let b = pixels[i + 2]

      // Apply brightness
      r = Math.min(255, Math.max(0, r + settings.brightness * 25.5))
      g = Math.min(255, Math.max(0, g + settings.brightness * 25.5))
      b = Math.min(255, Math.max(0, b + settings.brightness * 25.5))

      // Apply contrast
      const factor = (259 * (settings.contrast * 255 + 255)) / (255 * (259 - settings.contrast * 255))
      r = Math.min(255, Math.max(0, factor * (r - 128) + 128))
      g = Math.min(255, Math.max(0, factor * (g - 128) + 128))
      b = Math.min(255, Math.max(0, factor * (b - 128) + 128))

      let brightness = (0.299 * r + 0.587 * g + 0.114 * b) / 255
      if (settings.invert) brightness = 1 - brightness

      const charIndex = Math.floor(brightness * (chars.length - 1))
      row.push({
        char: chars[Math.min(charIndex, chars.length - 1)],
        r: Math.round(r),
        g: Math.round(g),
        b: Math.round(b),
      })
    }
    result.push(row)
  }

  return result
}

export function asciiToText(grid: AsciiChar[][]): string {
  return grid.map(row => row.map(c => c.char).join('')).join('\n')
}

export function asciiToHtml(grid: AsciiChar[][], settings: AsciiSettings): string {
  const isColor = settings.colorMode === 'color'
  let html = `<!DOCTYPE html>
<html><head><style>
body { background: #0a0a0a; margin: 0; display: flex; justify-content: center; align-items: center; min-height: 100vh; }
pre { font-family: 'JetBrains Mono', monospace; font-size: ${settings.fontSize}px; line-height: ${settings.lineHeight}; letter-spacing: 0; }
</style></head><body><pre>`

  for (const row of grid) {
    for (const c of row) {
      if (isColor) {
        html += `<span style="color:rgb(${c.r},${c.g},${c.b})">${c.char === ' ' ? '&nbsp;' : escapeHtml(c.char)}</span>`
      } else {
        html += c.char === ' ' ? '&nbsp;' : escapeHtml(c.char)
      }
    }
    html += '\n'
  }

  html += `</pre></body></html>`
  return html
}

export function asciiToJs(grid: AsciiChar[][], settings: AsciiSettings): string {
  const text = asciiToText(grid)
  return `// ASCII Art - Generated by ASC11 Clone
(function() {
  const pre = document.createElement('pre');
  pre.style.cssText = 'font-family: monospace; font-size: ${settings.fontSize}px; line-height: ${settings.lineHeight}; background: #0a0a0a; color: #e0e0e0; padding: 20px; white-space: pre;';
  pre.textContent = ${JSON.stringify(text)};
  document.body.appendChild(pre);
})();`
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}
